vich_uploader:
    db_driver: orm

    mappings:
        user_image:
           uri_prefix: /upload/users
           upload_destination: '%kernel.project_dir%/public/upload/users'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        event_image:
            uri_prefix: /upload/events
            upload_destination: '%kernel.project_dir%/public/upload/events'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        post_image:
            uri_prefix: /upload/posts
            upload_destination: '%kernel.project_dir%/public/upload/posts'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        club_image:
            uri_prefix: /upload/clubs
            upload_destination: '%kernel.project_dir%/public/upload/clubs'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer